### ISSUE TITLE
Make subcaptions compatible to beamer

### ISSUE THREAD

**Issue by samcarter8** [axelsommerfeldt/caption#4]
Your fantastic `subcaption` package is nearly compatible with beamer - it uses the correct colours and everything, just the font for the subcaptions is not set. Would it be possible to somehow fix this? Maybe add something like `\DeclareCaptionTextFormat{simple}{\usebeamerfont{caption}‌​#1}` in the beamer compatibility section of the caption package?

MWE to demonstrate this problem:

```
\documentclass{beamer}
\setbeamerfont{caption}{size=\tiny}
\setbeamercolor{caption}{fg=red}

\usepackage{subcaption}

\begin{document}

\begin{frame}  
	\begin{figure}
		\subcaptionbox{Original}{\includegraphics[scale=0.15]{example-image}}
		\subcaptionbox{New}{\includegraphics[scale=0.15]{example-image}}
		\caption{Image}
	\end{figure}
\end{frame}
\end{document}
```

**Comment by axelsommerfeldt** [comment]
Thanks for the report. I will take a look at it next week-end.

**Comment by axelsommerfeldt** [comment]
First off all sorry for being late. However I finally found some time to take a closer look at this issue.

The font set by `\setbeamerfont{caption}{...}` is already used by the caption package, otherwise the font used for the regular caption would be much larger. But the font size for sub-captions will be overwritten because `\usepackage{subcaption}` is equivalent to `\usepackage[size=small]{subcaption}` here.

The subcaption documentation says: "The default settings for subcaptions are: margin=0pt,font+=small,labelformat=parens,labelsep=space,
skip=6pt,list=false,hypcap=false"

So these are the options overwritten for sub-captions just by including the subcaption package. If one wants to change this, she/he needs to overwrite the default options, e.g.:

    \usepackage[font=tiny]{subcaption}

(Unfortunately "font=tiny" is missing in the caption package, but I just fixed that with commit 8088ac29f196076ab4b9a942f96d557a36cdec47.)

As an alternative one could use

    \usepackage[font=default]{subcaption}

to overwrite the font for sub-captions with the default font setting, which is `\usebeamerfont *{caption}\usebeamercolor [fg]{caption}` in beamer which is documented as "default value (of font=) is beamer “caption” settings" in section "beamer" of the caption package documentation.

I know this is some kind of confusing but deciding how to handle different caption settings (here: beamer caption settings vs. (sub)caption package settings) wasn't the easy part of writing the caption package. Maybe the subcaption package should use the beamer settings, too, if they have been altered by the user, but this would make the whole thing in-transparent and likely even more confusing!?

If you have an idea how to handle this situation in a better way (without breaking compatibility, if possible), please let me know.

**Comment by samcarter8** [comment]
Thanks a lot for having a look at this topic!

My personal opinion: I think the `subcaption` package should use beamer settings, for two simple reasons:
 
- the caption package does so too
- as far as I understand your code, the subcaption packages uses routines from the caption package to set the label `(a)`, these adhere to the beamer caption font size, thus making it very inconsistent:

![screen shot 2018-05-01 at 14 46 09](https://user-images.githubusercontent.com/8226363/39473294-6c236ab2-4d4e-11e8-9cab-c6cb1b52ff64.png)

I think at the moment this is really confusing for the users. 

Setting the font size in the subcaption package options works fine, however then it is not easy to understand why this is necessary, because for the caption package it works fine by using beamers own font mechanism with `\setbeamerfont{caption}{...}`

----

For me two approaches would make sense:

- using the beamer caption font for the subcaption (I'm not sure what the best technical approach to do this is, for my personal consumption I hacked `\DeclareCaptionTextFormat{simple}{\usebeamerfont{caption}‌​#1}`, but there is probably a cleaner way to do this)

- setting up a separate font template `\setbeamerfont{subcaption}{parent=caption}` which would inherent the font size from caption. However with this approach it the subcaption label `(a)` would need to be set using this font and not the caption font. (I have a slight preference for this, but no idea how difficult this would be)

**Comment by axelsommerfeldt** [comment]
The caption (and subcaption) package already uses the beamer settings. The problem is that these settings can be overwritten by `\captionsetup{...}` and this is what `\usepackage{subcaption}` partly does automatically.

When loading the caption package, the default font settings are:

    \usebeamerfont *{caption}
    \usebeamercolor [fg]{caption}

for the font setting and

    \usebeamerfont *{caption name}
    \usebeamercolor [fg]{caption name}

for the label font. By loading the subcaption package the first one gets overwritten with `\small` but the second one is left intact. For that reason the label will get the size setup for the beamer caption. If you load the subcaption package with `\usepackage[labelfont=]{subcaption}` the label will get the same size as the rest of the sub-caption.

But why is `\usebeamerfont *{caption name}` setting the font/size of the font/size setup for the caption? I have to take a look at the beamer code for answering this (but have no time for this today).

So currently I see three main problems here:

1. There is no standardized way of setting/getting font settings for specific parts like the caption or caption label/name. This is simply missing in LaTeX. The caption package and beamer have implemented their own interface for that purpose, and they are competing instead of incorporating. This is happening all the time since what LaTeX itself offers is not even nearly sufficient for most of the LaTeX document classes and packages. (Just take a look at KOMA-Script. It contains tons of stuff which should be part of LaTeX instead. And of course KOMA-Script has its very own way of setting/getting font settings for specific parts like the caption.) The LaTeX universe has grown rapidly in the last 20 years but LaTeX itself has not.

2. Why is `\usebeamerfont*{caption name}` setting the font size to tiny in your example?

3. Doing `font+=size` in subcaption is sub-optimal since this overwrites the font setting. What is really meant by introducing this setting is "use the current size, but a little smaller" but AFAIK there is no way to do this in LaTeX. So you run into the same problem without beamer, by writing

    \documentclass{article}
    \usepackage[size=tiny]{caption}
    \usepackage{subcaption}

Solutions:

1. Use ConTeXt instead of LaTeX. As long as one uses LaTeX one has to deal with competing concepts from different packages and incompatibilities between different packages or document classes and packages. And tons of missing interfaces, just to save a few bytes of RAM which was relevant 30 years ago. The whole LaTeX universe has become an incoherent and incompatible mess, and even basic concepts and interfaces are missing. This can only be solved by the LaTeX team, and I neither see the willing nor the manpower to do so.

2. One have to ask the author/maintainer of beamer why `\usebeamerfont*{caption name}` behaves this way. To me this looks strange. Why is it applying the font size set by `\setbeamerfont{caption}{...}`? Maybe the caption is typeset in beamer as `{\captionnamefont (a)}{\captionfont Blah...}`, and therefore the caption font is applied as well when the caption name font is applied? If yes this is incompatible to the caption package by design since the caption package typesets the caption (since 1994!) this way: `{\captionfont {\captionnamefont (a)}Blah...}`. (But this is just a guess, one have to take a look at the beamer sources. Maybe this is just a bug in beamer no-one has noticed before.)

3. I'm not aware of a clean solution. One could try all the font size setting commands (`\tiny`, `\small`, ...) to see if one of them matches the current setting. If yes, the code knows how to make the sub-caption smaller. I guess I will implement this (to overcome the 1000th LaTeX design flaw). But this would only solve this problem and not problem #2, so one would still get an arkward looking sub-caption with different caption label/name size and caption size.

**Comment by samcarter8** [comment]
Concerning `Why is \usebeamerfont*{caption name} setting the font size to tiny in your example?`

In my example I set `\setbeamerfont{caption}{size=\tiny}. The `caption name` font becomes tiny as well because it inherets the size from the caption size. (it is defined as `\setbeamerfont{caption name}{parent={structure,caption}}`)

**Comment by samcarter8** [comment]
```
I don't think that the `caption name` font is setting the size for the rest of the section:

\documentclass{beamer}

\setbeamerfont{caption name}{size=\huge}
\setbeamerfont{caption}{size=\tiny}
\setbeamercolor{caption}{fg=red}

\usepackage{subcaption}

\begin{document}

\begin{frame}  
	\begin{figure}
		\subcaptionbox{Original}{\includegraphics[scale=0.15]{example-image}}
		\subcaptionbox{New}{\includegraphics[scale=0.15]{example-image}}
		\caption{Image}
	\end{figure}
\end{frame}
\end{document}

```

**Comment by axelsommerfeldt** [comment]
Regarding problem no.2: Ok, that explains it, but how do I apply the beamer "caption name" settings without applying the beamer "caption" settings as well? (Because this is exactly what I need to do.)

Regarding problem no 3: Solved with commit 74ad8674ba0e67b715f2f73fbf9d8b5197baab25. (This was much easier than I thought it would be, and is IMHO a general improvement, not only when using beamer as document class.)

**Comment by samcarter8** [comment]
if you are asking how to make `caption name` font not inherit from the caption font

```
\documentclass{beamer}

\setbeamerfont{caption name}{parent={}}

\usepackage{subcaption}

\setbeamerfont{caption}{size=\tiny}
\setbeamercolor{caption}{fg=red}

\begin{document}

\begin{frame}  
	\begin{figure}
		\subcaptionbox{Original}{\includegraphics[scale=0.15]{example-image}}
		\subcaptionbox{New}{\includegraphics[scale=0.15]{example-image}}
		\caption{Image}
	\end{figure}
\end{frame}
\end{document}

```

**Comment by axelsommerfeldt** [comment]
Problem no. 2 fixed with commit 456aea55fcbde2e2a88c13ff2b8ad40aba2726cb.

Thanks a lot for your great help to resolve this issue. :+1: 

So at least in my opinion this issue can be closed. Do you agree?

**Comment by samcarter8** [comment]
Thanks a lot for all your time and effort you put into this! 

I just tested and I get a uniform font size. Great!

**Comment by axelsommerfeldt** [comment]
Prepared for CTAN release with commit a5a0e2b65478ed4fb8d1239cd933264479a1d0b2
